# permissions for end users to edit inferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inference-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube
    app.kubernetes.io/part-of: kube
    app.kubernetes.io/managed-by: kustomize
  name: inference-editor-role
rules:
- apiGroups:
  - serving.baize.io
  resources:
  - inferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.baize.io
  resources:
  - inferences/status
  verbs:
  - get
