# permissions for end users to view models.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube
    app.kubernetes.io/managed-by: kustomize
  name: serving-model-viewer-role
rules:
- apiGroups:
  - serving.baize.io
  resources:
  - models
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.baize.io
  resources:
  - models/status
  verbs:
  - get
